[tools]
aube = "latest"
node = "22"

[env]
PORT = "3000"

[tasks]
install = "aube install --locked"
webhook-deploy = "aube x partykit deploy"
update = "aube update"
envpush = "aube x partykit env push"
start = "aube run start"
ci = "mise oci build && mise oci push"

[deps]
aube = { auto = true }

[settings]
experimental = true
github_attestations = true

[oci]
from = "docker.io/debian:latest"
tag = "${github.repo}:latest"
workdir = "/app"
entrypoint = ["bash", "-l"]
cmd = []
user = "nonroot"
user_id = 1000
group_id = 1000
mount_point = "/mise"
labels = { "org.opencontainers.image.source" = "https://github.com/${github.repo}" }
