[tools]
aube = "latest"
node = "22"

[tasks]
install = "aube install"
webhook-deploy = "aube x partykit deploy"
update = "aube update"
envpush = "aube x partykit env push"
start = "aube run start"

[deps.aube]
auto = true

[settings]
experimental = true

[env]
PORT = 3000
